name: Deploy to Play Store
on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'android/**'

  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - beta
          - promote_to_production
          - production

# Declare default permissions as read only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v
        working-directory: .

      # Checkout code and get packages.
      - name: Checkout gallery code
        uses: actions/checkout@v3

      - run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: .

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/AndroidKey2022.jks
          echo "$KEY_PROPERTIES" | base64 --decode >> key.properties
          echo "$PLAY_STORE_CONFIG_JSON" > play-key.json
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}

      # Build and deploy with Fastlane (by default, to internal track) 🚀.
      - run: flutter build appbundle --build-number=${{ github.run_number }}
      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
