name: Deploy to Play Store
on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'android/**'

  pull_request:
    branches:
      - master

  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - beta
          - promote_to_production
          - production

# Declare default permissions as read only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout gallery code
        uses: actions/checkout@v3
      - run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      # - name: Setup Fastlane
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "2.6"
      #     bundler-cache: true
      #     working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/AndroidKey2022.jks
          echo "$KEY_PROPERTIES" | base64 --decode >> key.properties
          echo "$PLAY_STORE_CONFIG_JSON" > play-key.json
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to internal track) 🚀.
      - run: flutter build appbundle --build-number=${{ github.run_number }}

      - uses: addnab/docker-run-action@v3
        with:
          image: fastlanetools/fastlane:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            echo "hello from docker"
            cd /work/android
            bundle exec fastlane internal

      # - run: bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
      #   working-directory: android